select '****************************************';
show databases;
select '****************************************';
use mydb;
show tables;
select '****************************************';
select * from rs_user;
select '';
select * from rs_project;
select '';
select * from rs_demo_urls;
select '';
select * from rs_kukaro_urls;